spring:
  kakao:
    auth:
      client:
        XKmXtdv7YYq5P1vcNgn6TNC2vDUpptYQ
      redirect:
        http://localhost:3000/oauth/callback/kakao
  token:
    secret:
      asljkafspjJDJHLJdhaldkjfdsUDFasljfl
