spring:
  kakao:
    auth:
      client:
        e7c7f04925714790ff3fb7942ad5dbd1
      redirect:
        http://localhost:3000/oauth/callback/kakao
  token:
    secret:
      asljkafspjJDJHLJdhaldkjfdsUDFasljfl
